### ISSUE TITLE
wont work on this site

### ISSUE THREAD

**Issue by bitiza** [igorskyflyer/userscript-anti-anti-adblock#29]
doesn't work on https://www.rockmods.net/

**Comment by igorskyflyer** [comment]
Thanks for your input. I will check it out and try to make it work. Depending on the site's implementation of anti-adblock feature it may be possible - or not - to provide a working solution.

Either way, stay up to date with this issue's status. 😁

**Comment by igorskyflyer** [comment]
Unfortunately, due to the nature of how UserScripts work and what access to the browser API they have, it is **not** possible for a UserScript to block the given anti-adblock.

Fortunately, though, you could use an adblocker and subscribe to filter lists I maintain, in particular, you'll need:

- [AdVoid.Core](https://github.com/igorskyflyer/ad-void) and,
- [AdVoid.Scriptlets.AntiAntiAdBlock](https://github.com/igorskyflyer/ad-void/tree/main/scriptlets)

You'll need to add both filter lists to your adblocker and the anti-adblock bug will be gone, note, `AdVoid.Scriptlets.AntiAntiAdBlock` is the one doing the blocking on the particular site you mentioned.

😉

**Comment by bitiza** [comment]
Thanks boss

**Comment by igorskyflyer** [comment]
No prob, fam 😎
